name: Podman Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install --yes podman
      - name: Build and publish the container image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          printf '%s' "${DOCKER_PASS}" | podman login docker.io --username "${DOCKER_USER}" --password-stdin
          VERSION=${GITHUB_REF#"refs/heads/"} COMMIT_SHA=${GITHUB_SHA} INITIATOR=${GITHUB_ACTOR} make publish
